<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Contact;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{

    /** @var EntityManagerInterface $em */
    private $em;

    /**
     * ContactRepository constructor.
     * @param EntityManagerInterface $em
     * @param ClassMetadata $class
     */
    public function __construct(EntityManagerInterface $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

        $this->em = $em;
    }

    /**
     * @param Contact $contact
     * @return Contact
     */
    public function save(Contact $contact)
    {
        if (null === $contact->getId()) {
            $this->em->persist($contact);
        }
        $this->em->flush();

        return $contact;
    }

    /**
     * @param Contact $contact
     */
    public function delete(Contact $contact)
    {
        $this->em->remove($contact);
        $this->em->flush();
    }

    public function findUrlByContact()
    {

        $query = $this->getEntityManager()->createQuery(
            'SELECT fileUrl
                        FROM documents AS doc
                  LEFT JOIN contact AS con ON doc.contact_id = con.id
                        ORDER BY doc.uploadAt DESC'
        );

        return $query->getResult();
    }

}
