<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Delivery;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Query\AST\LikeExpression;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends \Doctrine\ORM\EntityRepository
{
    /** @var EntityManagerInterface $em */
    private $em;

    /**
     * CarRepository constructor.
     * @param EntityManagerInterface $em
     * @param ClassMetadata $class
     */
    public function __construct(EntityManagerInterface $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

        $this->em = $em;
    }

    /**
     * @param Delivery $delivery
     * @return Delivery
     * @throws \Exception
     */
    public function save(Delivery $delivery)
    {

        if (null === $delivery->getId()) {
            $this->em->persist($delivery);
        }
        $this->em->flush();

        return $delivery;
    }

    /**
     * @param Delivery $delivery
     */
    public function delete(Delivery $delivery)
    {
        $this->em->remove($delivery);
        $this->em->flush();
    }

    public function findByBarcode(int $barcodeNumber){

        return  $this->createQueryBuilder('b')
            ->select('barcode', 'b')
            ->from('b.deliveries', 'b')
            ->where('b.barcode LIKE :barcodeNumber')
            ->setParameter('barcodeNumber', $barcodeNumber . '%')
            ->addOrderBy('b.barcode')
            ->getQuery()
            ->setFirstResult(0)
            ->setMaxResults(10)
            ->getResult();
    }
    public function findBySaleProduct($productName){

//        $entityManage = $this->getEntityManager()->createQuery('
//             SELECT productName
//                FROM deliveries
//                    WHERE deliveries.productName LIKE :productName
//                    ORDER BY p.price ASC'
//        )->setParameter('productName', );
    }




}
