<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Message;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    /** @var EntityManagerInterface $em */
    private $em;

    /**
     * CarRepository constructor.
     * @param EntityManagerInterface $em
     * @param ClassMetadata $class
     */
    public function __construct(EntityManagerInterface $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

        $this->em = $em;
    }

    /**
     * @param Message $message
     * @return Message
     */
    public function save(Message $message)
    {
        if (null === $message->getId()) {
            $this->em->persist($message);
        }
        $this->em->flush();

        return $message;
    }

    /**
     * @param Message $message
     */
    public function delete(Message $message)
    {

        $this->em->remove($message);
        $this->em->flush();
    }

    public function findAllMessageSortedByDate(Message $message) {
        return $this->createQueryBuilder('m')
            ->where('m.message = :message')
            ->setParameter('message', $message)
            ->addOrderBy('m.dateAdded', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
