<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Supplier;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    /** @var EntityManagerInterface $em */
    private $em;

    /**
     * CarRepository constructor.
     * @param EntityManagerInterface $em
     * @param ClassMetadata $class
     */
    public function __construct(EntityManagerInterface $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

        $this->em = $em;
    }

    /**
     * @param Supplier $supplier
     * @return Supplier
     */
    public function save(Supplier $supplier)
    {
        if (null === $supplier->getId()) {
            $this->em->persist($supplier);
        }
        $this->em->flush();

        return $supplier;
    }

    /**
     * @param Supplier $supplier
     */
    public function delete(Supplier $supplier)
    {
        $this->em->remove($supplier);
        $this->em->flush();
    }
}
